services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: gigi
      MONGO_INITDB_ROOT_PASSWORD: taichi

  app:
    # Build image nodeserver from Dockerfile in GitHub repo
    image: nodejs-cicd
    build:
      context: https://github.com/CleverseAcademy/nodejs-cicd.git#develop
      args:
        FROM_REPO: https://github.com/CleverseAcademy/nodejs-cicd
        APP_VERSION: compose-develop
    environment:
      MONGODB_USERNAME: gigi
      MONGODB_PASSWORD: taichi
      MONGODB_HOST: mongodb
    ports:
      - "8000:8000"
