name: Build and push Docker image
run-name: "Triggering test by ${{ github.actor }}"

on:
  push:
    tags: "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out ${{ github.ref }} ${{ github.sha }}
        uses: actions/checkout@v3
      - name: Set up QEMU for Buildx
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: artnoi/nodejs-cicd:latest
