name: Test workflow
run-name: "Triggering test by ${{ github.actor }}"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test code on all platforms
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    uses: ./.github/workflows/test-template.yaml
    with:
      runs-on: ${{ matrix.os }}
